# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TookTook' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # For Initialization
  pod 'Tapa'

  # For Debug
  pod 'FLEX', :configurations => ['Debug']
  pod 'Gedatsu', configuration: %w(Debug)

  # For Firebase
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Core'
  pod 'FirebaseUI'
  pod 'GoogleSignIn'


  target 'TookTookTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
